Restaurant.create(name: 'Sottocasa NYC', address: '298 Atlantic Ave, Brooklyn, NY 11201')
Restaurant.create(name: 'PizzArte', address: '69 W 55th St, New York, NY 10019')
Restaurant.create(name: 'L\'Antica Pizzeria da Michele', address: '1250 2nd Ave, New York, NY 10065')
Restaurant.create(name: 'Roberta\'s', address: '261 Moore St, Brooklyn, NY 11206')

Pizza.create(name: 'Cheese', ingredients: 'Dough, Tomato Sauce, Cheese')
Pizza.create(name: 'Pepperoni', ingredients: 'Dough, Tomato Sauce, Cheese, Pepperoni')
Pizza.create(name: 'Margherita', ingredients: 'Dough, Tomato Sauce, Mozzarella, Basil')
Pizza.create(name: 'Hawaiian', ingredients: 'Dough, Tomato Sauce, Cheese, Ham, Pineapple')
Pizza.create(name: 'Vegetarian', ingredients: 'Dough, Tomato Sauce, Cheese, Bell Peppers, Mushrooms, Olives')

RestaurantPizza.create(restaurant: Restaurant.find(1), pizza: Pizza.find(1), price: 10)
RestaurantPizza.create(restaurant: Restaurant.find(1), pizza: Pizza.find(2), price: 12)
RestaurantPizza.create(restaurant: Restaurant.find(2), pizza: Pizza.find(3), price: 11)
RestaurantPizza.create(restaurant: Restaurant.find(2), pizza: Pizza.find(4), price: 13)
RestaurantPizza.create(restaurant: Restaurant.find(3), pizza: Pizza.find(1), price: 9)
RestaurantPizza.create(restaurant: Restaurant.find(3), pizza: Pizza.find(3), price: 10)
RestaurantPizza.create(restaurant: Restaurant.find(3), pizza: Pizza.find(5), price: 11)
RestaurantPizza.create(restaurant: Restaurant.find(4), pizza: Pizza.find(2), price: 12)
RestaurantPizza.create(restaurant: Restaurant.find(4), pizza: Pizza.find(4), price: 14)
RestaurantPizza.create(restaurant: Restaurant.find(4), pizza: Pizza.find(5), price: 13)
